# Describes the format for available Netatmo services
set_schedule:
  description: Set the heating schedule.
  fields:
    schedule_name:
      description: Schedule name.
      example: Standard
    home_name:
      description: Home name.
      example: MyHome

set_persons_home:
  description: Set a person as away from home
  fields:
    home_name:
      description: The name of the house
      example: Home
    persons:
      descriotion: A list of persons to set as at home
      example: [john, jack]
    
